apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: root-app-directory-approach
  name: root-app-directory-approach
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  project: default
  source:
    path: directory-of-apps
    repoURL: https://github.com/theadityab/argo-root.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: null

