apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elements-yaml
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: git@github.com:theadityab/argo-root.git
          revision: main
          files:
          - path: argocd/environments/*/applist.yaml
      - list:
          elements: []
          elementsYaml: "{{ .key.components | toJson }}"
  template:
    metadata:
      name: '{{ .name }}-{{.path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true        
      sources:
        - repoURL: git@github.com:theadityab/argo-testing.git
          targetRevision: '{{ .targetversion }}'
          path: helm-charts/my-apps
          helm:
            valueFiles:
            - ../../k8sconfig/apps/{{ .name }}/{{.path.basename}}-version.yaml
            - ../../appconfig/global-values.yaml
            - ../../appconfig/environments/{{.path.basename}}-values.yaml
            parameters:
            - name: "deployment.image.tag"
              value: '{{ .tagname }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
