defaults: &defaultValues
  targetversion: release-9.1
key:
  components:
    - name: core
      <<: *defaultValues
      tagname: v4
      disableAutoSync: true
    - name: admin 
      <<: *defaultValues 
      tagname: v2
      
      
