defaults: &defaultValues
  targetversion: release-9.1
key:
  components:
    - name: core
      <<: *defaultValues
      tagname: v1
    - name: admin
      targetversion: release-9.1
      tagname: v2
