defaults: &defaultValues
  targetversion: release-8.1
key:
  components:
    - name: core
      <<: *defaultValues
      tagname: v4
    # - name: admin
    #   targetversion: release-9.1
    #   tagname: v2
